# Generated by Django 3.1.7 on 2021-03-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210328_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=40)),
                ('review_body', models.TextField(blank=True, null=True)),
                ('review_pic', models.ImageField(blank=True, null=True, upload_to='featured-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('courses', models.CharField(max_length=40)),
                ('detail', models.TextField(blank=True, null=True)),
                ('subject_pic', models.ImageField(blank=True, null=True, upload_to='featured-images/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
